import { NextRequest, NextResponse } from "next/server";
import { applySessionOutcome, authorizedCall, bffErrorResponse, createBackendClient } from "@/lib/auth/bff";
import { errorMessageFor } from "@/lib/auth/ui-messages";
import type { BackendAvailabilityWrite } from "@/lib/auth/contracts";
type Context = { params: Promise<{ salonId: string; profileId: string; availabilityId: string }> };
const fields = ["day_of_week", "start_time", "end_time"] as const;
function valid(body: unknown): body is BackendAvailabilityWrite { if (!body || typeof body !== "object" || Array.isArray(body)) return false; const record = body as Record<string, unknown>; if (!Object.keys(record).length || Object.keys(record).some((key) => !fields.includes(key as typeof fields[number]))) return false; if ("day_of_week" in record && (!Number.isInteger(record.day_of_week) || Number(record.day_of_week) < 0 || Number(record.day_of_week) > 6)) return false; for (const key of ["start_time", "end_time"] as const) if (key in record && (typeof record[key] !== "string" || !/^([01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?$/.test(record[key] as string))) return false; return !(("start_time" in record && record.start_time === null) || ("end_time" in record && record.end_time === null)); }
function finish(req: NextRequest, outcome: Awaited<ReturnType<typeof authorizedCall<unknown>>>, deleted = false) { if (!outcome.result.ok) { const res = bffErrorResponse(outcome.result.code, errorMessageFor(outcome.result.code, outcome.result.retryAfterSeconds)); applySessionOutcome(res, outcome); return res; } const res = deleted ? new NextResponse(null, { status: 204 }) : NextResponse.json({ ok: true, slot: outcome.result.data }); applySessionOutcome(res, outcome); return res; }
export async function PATCH(req: NextRequest, { params }: Context) { const { salonId, profileId, availabilityId } = await params; let body: unknown; try { body = await req.json(); } catch { return bffErrorResponse("validation_error", "Periksa jadwal yang dimasukkan.", undefined, 422); } if (!valid(body)) return bffErrorResponse("validation_error", "Periksa hari dan rentang waktu.", undefined, 422); const backend = createBackendClient(); return finish(req, await authorizedCall({ backend, req }, (token) => backend.updateAvailability(token, salonId, profileId, availabilityId, body))); }
export async function DELETE(req: NextRequest, { params }: Context) { const { salonId, profileId, availabilityId } = await params; const backend = createBackendClient(); return finish(req, await authorizedCall({ backend, req }, (token) => backend.deleteAvailability(token, salonId, profileId, availabilityId)), true); }
