"""phase 4 branch domain foundation

Revision ID: d3ee55b72596
Revises: 9ecad5e4f77e
Create Date: 2026-10-02 06:40:53.088515

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3ee55b72596"
down_revision: str | Sequence[str] | None = "9ecad5e4f77e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "branches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("salon_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["salon_id"],
            ["salons.id"],
            name=op.f("fk_branches_salon_id_salons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_branches")),
        sa.UniqueConstraint("salon_id", "code", name="uq_branches_salon_code"),
    )
    op.create_index(op.f("ix_branches_salon_id"), "branches", ["salon_id"], unique=False)
    op.create_index(
        "ix_branches_salon_is_active", "branches", ["salon_id", "is_active"], unique=False
    )

    # P4-A: Default branch migration for backward compatibility
    # Uses Asia/Jakarta as system default timezone (consistent with Phase 3 appointment tests)
    op.execute(
        """
        INSERT INTO branches (id, salon_id, name, code, timezone, is_active, created_at, updated_at)
        SELECT 
            gen_random_uuid(),
            id,
            'Main Branch',
            'main',
            'Asia/Jakarta',
            true,
            now(),
            now()
        FROM salons
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_branches_salon_is_active", table_name="branches")
    op.drop_index(op.f("ix_branches_salon_id"), table_name="branches")
    op.drop_table("branches")
    # ### end Alembic commands ###
