"use client";
import { useCallback, useEffect, useState } from "react";
import type { AppointmentStatus, BackendAppointment, BackendAvailability, BackendSalonCustomer, BackendSalonService, BackendStaffProfile } from "@/lib/auth/contracts";
import { Alert, Button } from "@/components/ui";

interface Props { salonId: string }
const statuses: AppointmentStatus[] = ["scheduled", "confirmed", "completed", "cancelled", "no_show"];
const statusLabels: Record<AppointmentStatus, string> = { scheduled: "Terjadwal", confirmed: "Dikonfirmasi", completed: "Selesai", cancelled: "Dibatalkan", no_show: "Tidak hadir" };
function localDate(date: Date) { const y = date.getFullYear(), m = String(date.getMonth() + 1).padStart(2, "0"), d = String(date.getDate()).padStart(2, "0"); return `${y}-${m}-${d}`; }
function weekStart(value: string) { const result = new Date(`${value}T12:00:00`); result.setDate(result.getDate() - ((result.getDay() + 6) % 7)); return result; }
export default function AppointmentCalendar({ salonId }: Props) {
  const [date, setDate] = useState(() => localDate(new Date())), [view, setView] = useState<"day" | "week">("day"), [appointments, setAppointments] = useState<BackendAppointment[]>([]), [customers, setCustomers] = useState<BackendSalonCustomer[]>([]), [services, setServices] = useState<BackendSalonService[]>([]), [staff, setStaff] = useState<BackendStaffProfile[]>([]), [availability, setAvailability] = useState<{ profileId: string; slots: BackendAvailability[] } | null>(null);
  const [status, setStatus] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false), [creating, setCreating] = useState(false);
  const [form, setForm] = useState({ customer_id: "", service_id: "", staff_profile_id: "", start: "", timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC", notes: "" });
  const root = `/api/salons/${encodeURIComponent(salonId)}`;
  const load = useCallback(async () => {
    const start = view === "week" ? weekStart(date) : new Date(`${date}T00:00:00`), end = new Date(start); end.setDate(end.getDate() + (view === "week" ? 7 : 1));
    const query = new URLSearchParams({ starts_at_gte: start.toISOString(), starts_at_lte: end.toISOString(), limit: "100" }); if (status) query.set("status", status);
    const response = await fetch(`${root}/appointments?${query}`), data = await response.json(); if (!response.ok) throw new Error(data.message ?? "Janji temu tidak dapat dimuat."); setAppointments(data.appointments);
  }, [date, root, status, view]);
  useEffect(() => { let live = true; Promise.all([fetch(`${root}/customers`).then((r) => r.json()), fetch(`${root}/services`).then((r) => r.json()), fetch(`${root}/staff-profiles`).then((r) => r.json())]).then(([c, s, p]) => { if (live) { setCustomers(c.customers ?? []); setServices((s.services ?? []).filter((x: BackendSalonService) => x.is_active)); setStaff((p.profiles ?? []).filter((x: BackendStaffProfile) => x.is_bookable)); } }).catch(() => { if (live) setError("Data pilihan janji temu tidak dapat dimuat."); }); return () => { live = false; }; }, [root]);
  useEffect(() => { let live = true; void Promise.resolve().then(load).catch((e: unknown) => { if (live) setError(e instanceof Error ? e.message : "Janji temu tidak dapat dimuat."); }); return () => { live = false; }; }, [load]);
  useEffect(() => { let live = true; if (!form.staff_profile_id) return () => { live = false; }; fetch(`${root}/staff-profiles/${encodeURIComponent(form.staff_profile_id)}/availability`).then((r) => r.json().then((d) => ({ r, d }))).then(({ r, d }) => { if (!r.ok) throw new Error(); if (live) setAvailability({ profileId: form.staff_profile_id, slots: d.slots ?? [] }); }).catch(() => { if (live) setError("Jadwal kerja staf tidak dapat dimuat."); }); return () => { live = false; }; }, [form.staff_profile_id, root]);
  async function mutate(url: string, method: string, body?: unknown) { setBusy(true); setError(""); try { const response = await fetch(url, { method, headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const data = await response.json(); if (!response.ok) throw new Error(data.message ?? (response.status === 409 ? "Waktu tersebut bertabrakan dengan janji temu lain." : "Perubahan janji temu gagal.")); await load(); setCreating(false); } catch (e) { setError(e instanceof Error ? e.message : "Terjadi kesalahan."); } finally { setBusy(false); } }
  function move(days: number) { const next = new Date(`${date}T12:00:00`); next.setDate(next.getDate() + days); setDate(localDate(next)); }
  const selectedService = services.find((service) => service.id === form.service_id);
  const selectedDay = form.start ? new Date(`${form.start.slice(0, 10)}T12:00:00`).getDay() : -1;
  const dayAvailability = (availability?.profileId === form.staff_profile_id ? availability.slots : []).filter((slot) => slot.is_available && slot.day_of_week === selectedDay);
  const suggestedTimes = dayAvailability.flatMap((slot) => { const [startHour, startMinute] = slot.start_time.split(":").map(Number); const [endHour, endMinute] = slot.end_time.split(":").map(Number); const start = startHour * 60 + startMinute, end = endHour * 60 + endMinute; const duration = selectedService?.duration_minutes ?? 30; const results: string[] = []; for (let minute = start; minute + duration <= end; minute += 30) results.push(`${String(Math.floor(minute / 60)).padStart(2, "0")}:${String(minute % 60).padStart(2, "0")}`); return results; });
  return <section className="mx-auto max-w-6xl px-4 py-8 sm:px-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">Janji Temu</h1><p className="mt-1 text-sm text-zinc-600">Jadwal {view === "day" ? "harian" : "mingguan"}. Waktu ditampilkan dalam zona waktu perangkat.</p></div><div className="flex flex-wrap items-center gap-2"><Button type="button" onClick={() => move(view === "week" ? -7 : -1)}>{view === "week" ? "Minggu sebelumnya" : "Hari sebelumnya"}</Button><input aria-label="Tanggal jadwal" type="date" value={date} onChange={(e) => setDate(e.target.value)} className="rounded border px-3 py-2"/><Button type="button" onClick={() => move(view === "week" ? 7 : 1)}>{view === "week" ? "Minggu berikutnya" : "Hari berikutnya"}</Button><label className="text-sm">Tampilan<select aria-label="Tampilan kalender" className="ml-2 rounded border p-2" value={view} onChange={(e) => setView(e.target.value as "day" | "week")}><option value="day">Hari</option><option value="week">Minggu</option></select></label><Button type="button" onClick={() => setCreating(!creating)}>Buat janji</Button></div></div>
    {error && <div className="mt-4"><Alert tone="error">{error}</Alert></div>}
    {creating && <form className="mt-6 grid gap-3 rounded-xl border p-4 sm:grid-cols-2 lg:grid-cols-3" onSubmit={(e) => { e.preventDefault(); const start = new Date(form.start); void mutate(`${root}/appointments`, "POST", { customer_id: form.customer_id, service_id: form.service_id, staff_profile_id: form.staff_profile_id, starts_at: start.toISOString(), timezone: form.timezone, notes: form.notes.trim() || null }); }}>
      <label className="text-sm">Pelanggan<select required className="mt-1 block w-full rounded border p-2" value={form.customer_id} onChange={(e) => setForm({ ...form, customer_id: e.target.value })}><option value="">Pilih pelanggan</option>{customers.map((c) => <option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label>
      <label className="text-sm">Layanan<select required className="mt-1 block w-full rounded border p-2" value={form.service_id} onChange={(e) => setForm({ ...form, service_id: e.target.value })}><option value="">Pilih layanan</option>{services.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
      <label className="text-sm">Staf<select required className="mt-1 block w-full rounded border p-2" value={form.staff_profile_id} onChange={(e) => setForm({ ...form, staff_profile_id: e.target.value })}><option value="">Pilih staf</option>{staff.map((p) => <option key={p.id} value={p.id}>{p.display_name || p.id}</option>)}</select></label>
      <label className="text-sm">Tanggal dan waktu<input required type="datetime-local" className="mt-1 block w-full rounded border p-2" value={form.start} onChange={(e) => setForm({ ...form, start: e.target.value })}/></label>
      <fieldset className="rounded border p-3 sm:col-span-2 lg:col-span-3"><legend className="px-1 text-sm font-medium">Waktu saran dari jam kerja</legend>{!form.staff_profile_id || !form.service_id || !form.start ? <p className="text-sm text-zinc-600">Pilih staf, layanan, tanggal dan waktu untuk melihat saran.</p> : suggestedTimes.length ? <div className="flex flex-wrap gap-2">{suggestedTimes.map((time) => <Button key={time} type="button" onClick={() => setForm({ ...form, start: `${form.start.slice(0, 10)}T${time}` })}>{time}</Button>)}</div> : <p className="text-sm text-zinc-600">Tidak ada jam kerja tercatat untuk hari ini.</p>}<p className="mt-2 text-xs text-zinc-500">Saran mengikuti jam kerja mingguan dan durasi layanan; tidak menjamin bebas konflik. Server memvalidasi ketersediaan saat disimpan.</p></fieldset>
      <label className="text-sm">Zona waktu IANA<input required className="mt-1 block w-full rounded border p-2" value={form.timezone} onChange={(e) => setForm({ ...form, timezone: e.target.value })}/></label>
      <label className="text-sm">Catatan (opsional)<input className="mt-1 block w-full rounded border p-2" maxLength={1000} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })}/></label>
      <div className="flex gap-2"><Button type="submit" disabled={busy}>Simpan</Button><Button type="button" onClick={() => setCreating(false)}>Batal</Button></div>
    </form>}
    <div className="mt-6 flex items-center gap-2"><label htmlFor="appointment-status" className="text-sm">Status:</label><select id="appointment-status" className="rounded border p-2" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Semua</option>{statuses.map((s) => <option key={s} value={s}>{statusLabels[s]}</option>)}</select></div>
    <div className="mt-4 overflow-x-auto rounded-xl border"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-zinc-50"><tr>{view === "week" && <th className="p-3">Tanggal</th>}<th className="p-3">Waktu</th><th className="p-3">Layanan</th><th className="p-3">Status</th><th className="p-3">Harga</th><th className="p-3">Tindakan</th></tr></thead><tbody>{appointments.map((a) => <tr key={a.id} className="border-t">{view === "week" && <td className="p-3">{new Intl.DateTimeFormat(undefined, { weekday: "short", day: "numeric", month: "short", timeZone: a.timezone }).format(new Date(a.starts_at))}</td>}<td className="p-3">{new Intl.DateTimeFormat(undefined, { hour: "2-digit", minute: "2-digit", timeZone: a.timezone }).format(new Date(a.starts_at))} · {a.timezone}</td><td className="p-3">{a.service_name_snapshot}<span className="block text-xs text-zinc-500">{a.duration_minutes_snapshot} menit</span></td><td className="p-3">{statusLabels[a.status]}</td><td className="p-3">{a.currency_snapshot} {a.price_amount_snapshot}</td><td className="p-3"><div className="flex flex-wrap gap-1">{a.status === "scheduled" && <Button disabled={busy} onClick={() => void mutate(`${root}/appointments/${a.id}/confirm`, "POST")}>Konfirmasi</Button>}{["scheduled", "confirmed"].includes(a.status) && <><Button disabled={busy} onClick={() => void mutate(`${root}/appointments/${a.id}/complete`, "POST")}>Selesai</Button><Button disabled={busy} onClick={() => void mutate(`${root}/appointments/${a.id}/no-show`, "POST")}>Tidak hadir</Button><Button disabled={busy} onClick={() => { const start = prompt("Waktu mulai ISO 8601 dengan offset zona waktu"); const timezone = start ? prompt("Zona waktu IANA", a.timezone) : null; if (start && timezone) void mutate(`${root}/appointments/${a.id}`, "PATCH", { starts_at: start, timezone }); }}>Jadwalkan ulang</Button><Button disabled={busy} onClick={() => void mutate(`${root}/appointments/${a.id}/cancel`, "POST")}>Batalkan</Button></>}</div></td></tr>)}{appointments.length === 0 && <tr><td colSpan={view === "week" ? 6 : 5} className="p-8 text-center text-zinc-500">Tidak ada janji temu pada rentang ini.</td></tr>}</tbody></table></div>
  </section>;
}
