"use client";
import { useCallback, useEffect, useState } from "react";
import type { BackendMembership, BackendSalonService, BackendStaffAssignment, BackendStaffProfile, TenantRole } from "@/lib/auth/contracts";
type Props = { salonId: string; membershipId: string; role: TenantRole };
export default function StaffProfiles({ salonId, membershipId, role }: Props) {
 const [profiles,setProfiles]=useState<BackendStaffProfile[]>([]),[members,setMembers]=useState<BackendMembership[]>([]),[services,setServices]=useState<BackendSalonService[]>([]),[assignments,setAssignments]=useState<Record<string,BackendStaffAssignment[]>>({}),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const admin=role==="owner"||role==="manager";
 async function request(path:string,method="GET",body?:unknown){const response=await fetch(path,{method,headers:body?{"content-type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(response.status===404?"Data tidak ditemukan (404).":response.status===409?"Perubahan bertentangan dengan data yang ada (409).":response.status===422?"Data tidak valid (422).":"Permintaan gagal.");return payload;}
 const load=useCallback(async()=>{try{const [p,m,s]=await Promise.all([request(`/api/salons/${salonId}/staff-profiles`),admin?request(`/api/salons/${salonId}/members`):Promise.resolve({members:[]}),request(`/api/salons/${salonId}/services`)]);setProfiles(p.profiles);setMembers((m.members as BackendMembership[]).filter(x=>x.status==="active"&&!p.profiles.some((profile:BackendStaffProfile)=>profile.membership_id===x.id)));setServices(s.services);const pairs=await Promise.all(p.profiles.map(async(profile:BackendStaffProfile)=>[profile.id,(await request(`/api/salons/${salonId}/staff-profiles/${profile.id}/services`)).assignments] as const));setAssignments(Object.fromEntries(pairs));}catch(e){setError(e instanceof Error?e.message:"Gagal memuat profil.");}},[salonId,admin]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 async function act(action:()=>Promise<unknown>){setBusy(true);setError("");try{await action();await load();}catch(e){setError(e instanceof Error?e.message:"Permintaan gagal.");}finally{setBusy(false);}}
 return <section className="mx-auto max-w-5xl space-y-6 px-4 py-8"><header><h1 className="text-2xl font-semibold">Profil Staf</h1><p className="mt-1 text-sm text-zinc-600">Kelola profil dan layanan yang dapat ditangani staf.</p></header>{error&&<p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-800">{error}</p>}{admin&&<form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void act(()=>request(`/api/salons/${salonId}/staff-profiles`,"POST",{membership_id:form.get("member")}));}}><select aria-label="Anggota salon" name="member" required className="rounded border px-3 py-2"><option value="">Pilih anggota aktif</option>{members.map(m=><option key={m.id} value={m.id}>{m.user.email} · {m.role}</option>)}</select><button disabled={busy||!members.length} className="rounded bg-zinc-900 px-4 py-2 text-white">Buat profil</button></form>}{profiles.map(profile=>{const editable=admin||profile.membership_id===membershipId;const assigned=(assignments[profile.id]??[]).map(a=>a.salon_service_id);return <article key={profile.id} className="space-y-4 rounded-xl border p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">{profile.display_name||`Profil ${profile.id.slice(0,8)}`}</h2>{admin&&<button disabled={busy} onClick={()=>void act(()=>request(`/api/salons/${salonId}/staff-profiles/${profile.id}/toggle-bookable`,"POST",{is_bookable:!profile.is_bookable}))} className="rounded border px-3 py-2">{profile.is_bookable?"Nonaktifkan untuk booking":"Aktifkan untuk booking"}</button>}</div>{editable&&<form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void act(()=>request(`/api/salons/${salonId}/staff-profiles/${profile.id}`,"PATCH",Object.fromEntries(["display_name","phone","bio","photo_url"].map(k=>[k,form.get(k)||null]))));}}>{(["display_name","phone","bio","photo_url"] as const).map(key=><label key={key} className="grid gap-1 text-sm">{key.replace("_"," ")}<input name={key} defaultValue={profile[key]??""} className="rounded border px-3 py-2" /></label>)}<button disabled={busy} className="w-fit rounded bg-zinc-900 px-4 py-2 text-white">Simpan profil</button></form>}<div><h3 className="mb-2 text-sm font-medium">Layanan</h3><div className="flex flex-wrap gap-3">{services.map(service=><label key={service.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={assigned.includes(service.id)} disabled={!admin||busy} onChange={e=>void act(()=>request(`/api/salons/${salonId}/staff-profiles/${profile.id}/services/${service.id}`,e.target.checked?"POST":"DELETE"))} />{service.name}</label>)}</div></div></article>})}{!profiles.length&&!error&&<p className="text-sm text-zinc-600">Belum ada profil staf.</p>}</section>;
}
