"use client";
import { useCallback, useEffect, useState } from "react";
import type { BackendAvailability, BackendStaffProfile } from "@/lib/auth/contracts";

const days = ["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"];
type Props = { salonId: string; membershipId: string; role: string };
async function request<T>(url: string, method = "GET", body?: unknown): Promise<T> {
  const response = await fetch(url, { method, headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined });
  if (!response.ok) { const payload = await response.json().catch(() => ({})); if (response.status === 409) throw new Error("Jadwal bertumpang tindih atau menggunakan waktu mulai yang sama."); if (response.status === 403) throw new Error("Anda tidak memiliki izin untuk mengubah jadwal ini."); throw new Error(payload.message ?? "Permintaan jadwal gagal."); }
  return response.status === 204 ? undefined as T : response.json();
}
export default function WeeklyAvailability({ salonId, membershipId, role }: Props) {
  const [profiles, setProfiles] = useState<BackendStaffProfile[]>([]); const [slots, setSlots] = useState<BackendAvailability[]>([]); const [selected, setSelected] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const admin = role === "owner" || role === "manager";
  const loadProfiles = useCallback(async () => { const result = await request<{ profiles: BackendStaffProfile[] }>(`/api/salons/${salonId}/staff-profiles`); setProfiles(result.profiles); setSelected((current) => current || result.profiles[0]?.id || ""); }, [salonId]);
  const loadSlots = useCallback(async () => { if (!selected) return; const result = await request<{ slots: BackendAvailability[] }>(`/api/salons/${salonId}/staff-profiles/${selected}/availability`); setSlots(result.slots); }, [salonId, selected]);
  useEffect(() => { const timer = window.setTimeout(() => { void loadProfiles().catch((e: unknown) => setError(e instanceof Error ? e.message : "Gagal memuat profil.")); }, 0); return () => window.clearTimeout(timer); }, [loadProfiles]);
  useEffect(() => { const timer = window.setTimeout(() => { if (selected) void loadSlots().catch((e: unknown) => setError(e instanceof Error ? e.message : "Gagal memuat jadwal.")); }, 0); return () => window.clearTimeout(timer); }, [loadSlots, selected]);
  async function act(action: () => Promise<unknown>) { setBusy(true); setError(""); try { await action(); await loadSlots(); } catch (e) { setError(e instanceof Error ? e.message : "Permintaan gagal."); } finally { setBusy(false); } }
  const profile = profiles.find((item) => item.id === selected); const canEdit = admin || profile?.membership_id === membershipId;
  function submit(event: React.FormEvent<HTMLFormElement>, slot?: BackendAvailability) { event.preventDefault(); const form = new FormData(event.currentTarget); const body = { day_of_week: Number(form.get("day")), start_time: form.get("start") as string, end_time: form.get("end") as string }; if (body.day_of_week < 0 || body.day_of_week > 6 || body.start_time >= body.end_time) { setError("Pilih hari dan waktu selesai setelah waktu mulai."); return; } void act(() => request(`/api/salons/${salonId}/staff-profiles/${selected}/availability${slot ? `/${slot.id}` : ""}`, slot ? "PATCH" : "POST", body)); if (!slot) event.currentTarget.reset(); }
  return <section className="mx-auto max-w-5xl space-y-6 px-4 py-8"><header><h1 className="text-2xl font-semibold">Ketersediaan Mingguan</h1><p className="mt-1 text-sm text-zinc-600">Atur jam ketersediaan tiap profil staf.</p></header>{error && <p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-800">{error}</p>}<label className="grid max-w-sm gap-1 text-sm">Profil staf<select value={selected} onChange={(event) => setSelected(event.target.value)} className="rounded border px-3 py-2">{profiles.map((item) => <option key={item.id} value={item.id}>{item.display_name || `Profil ${item.id.slice(0, 8)}`}</option>)}</select></label>{!profiles.length && <p className="text-sm text-zinc-600">Belum ada profil staf.</p>}{slots.length === 0 && profiles.length > 0 && <p className="text-sm text-zinc-600">Belum ada jadwal untuk profil ini.</p>}{days.map((day, index) => <section key={day} className="space-y-2"><h2 className="font-medium">{day}</h2>{slots.filter((slot) => slot.day_of_week === index).map((slot) => <form key={slot.id} onSubmit={(event) => submit(event, slot)} className="flex flex-wrap items-end gap-2 rounded-lg border p-3"><input aria-label={`${day} hari`} name="day" type="hidden" value={index} /><label className="grid gap-1 text-sm">Mulai<input name="start" type="time" required defaultValue={slot.start_time.slice(0, 5)} disabled={!canEdit || busy} className="rounded border px-2 py-1" /></label><label className="grid gap-1 text-sm">Selesai<input name="end" type="time" required defaultValue={slot.end_time.slice(0, 5)} disabled={!canEdit || busy} className="rounded border px-2 py-1" /></label>{canEdit && <><button disabled={busy} className="rounded bg-zinc-900 px-3 py-2 text-sm text-white">Simpan</button><button type="button" disabled={busy} onClick={() => void act(() => request(`/api/salons/${salonId}/staff-profiles/${selected}/availability/${slot.id}`, "DELETE"))} className="rounded border px-3 py-2 text-sm">Hapus</button></>}</form>)}</section>)}{canEdit && selected && <form onSubmit={(event) => submit(event)} className="flex flex-wrap items-end gap-2 rounded-lg bg-zinc-50 p-4"><label className="grid gap-1 text-sm">Hari<select name="day" required className="rounded border px-2 py-2">{days.map((day, index) => <option key={day} value={index}>{day}</option>)}</select></label><label className="grid gap-1 text-sm">Mulai<input name="start" type="time" required className="rounded border px-2 py-2" /></label><label className="grid gap-1 text-sm">Selesai<input name="end" type="time" required className="rounded border px-2 py-2" /></label><button disabled={busy} className="rounded bg-zinc-900 px-4 py-2 text-white">Tambah jadwal</button></form>}</section>;
}
